Gaming.MVC/Controllers/BotController.cs
using Gaming.MVC.Attributes;
using Gaming.MVC.Models;
using Gaming.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using Telegram.Bot;
using Telegram.Bot.Types;

namespace Gaming.MVC.Controllers;



public class BotController : Controller
{
    
    private readonly TelegramBotService _telegram;

    public BotController(TelegramBotService telegram)
    {
        
        _telegram = telegram;
    }



    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Post([FromForm] ContactSended feedback)
    {

        
        if(ModelState.IsValid)
        {
            
            //33780774

           
            var fixedMessage = $"Name:{feedback.ContactUs.Name}\nEmail:{feedback.ContactUs.Email}\nSurname:{feedback.ContactUs.Surname}\nSubject:{feedback.ContactUs.Subject}\nMessage:{feedback.ContactUs.Message}";

            await _telegram.GetBot().SendTextMessageAsync(33780774, fixedMessage);

            feedback.IsSended = true;

            return RedirectToAction("Contact", "Home",feedback);
        }
        return RedirectToAction("Index","Home");
       
    }

    //[HttpPost("/api/bot")]
    //public Task<IActionResult> TelegramUpdate(Update update)
    //{
        
    //}
  
}

Gaming.MVC/Controllers/CartsController.cs
using Gaming.Application.Common.Interfaces;
using Gaming.Domain.Entities;
using Gaming.Infrastructure.DataAccsess;
using Gaming.MVC.Controllers;
using Gaming.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;

namespace UserIdentitySolution.Controllers
{
    [Authorize]
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICurrentUser _currentUser;
        public CartsController(ApplicationDbContext context, ICurrentUser currentUser)
        {
            _context = context;
            _currentUser = currentUser;
        }

        // GET: Carts

        [EnableRateLimiting("FixedLimiter")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Carts.Include(c => c.Product).Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.Product)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CartId == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CartId,UserId,ProductId,Quantity")] Cart cart)
        {
         

            if (ModelState.IsValid)
            {
                cart.CartId = Guid.NewGuid();
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", cart.ProductId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", cart.UserId);
            return View(cart);
        }

        
        public async Task<IActionResult> CreateCart(Guid productId, int quantity)
        {
            var currentUserId = _currentUser.UserId;
            if(currentUserId is null) { return NotFound(); }
            if (ModelState.IsValid)
            {
                Cart cart = new Cart
                {
                    ProductId =productId,
                    Quantity = quantity,
                    UserId = currentUserId,
                    CartId = Guid.NewGuid()
                };
                await _context.Carts.AddAsync(cart);
                await _context.SaveChangesAsync();

                return RedirectToAction("OurShop","Home");
                
            }
            return NoContent();
        }



        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", cart.ProductId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", cart.UserId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CartId,UserId,ProductId,Quantity")] Cart cart)
        {
            if (id != cart.CartId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.CartId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", cart.ProductId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", cart.UserId);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Carts == null)
            {
                return NotFound();
            }

            var cart = await _context.Carts
                .Include(c => c.Product)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CartId == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Carts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Carts'  is null.");
            }
            var cart = await _context.Carts.FindAsync(id);
            if (cart != null)
            {
                _context.Carts.Remove(cart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(Guid id)
        {
          return (_context.Carts?.Any(e => e.CartId == id)).GetValueOrDefault();
        }
    }
}

Gaming.MVC/Controllers/HomeController.cs
using Gaming.Domain.Entities;
using Gaming.MVC.Models;
using LazyCache;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;
using System.Diagnostics;
using X.PagedList;

namespace Gaming.MVC.Controllers;

[Authorize]
public class HomeController : BaseController
{
    private readonly ILogger<HomeController> _logger;
   
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
        
    }

    [EnableCors(PolicyName = "pdpmetan")]
    
    public async ValueTask<IActionResult> Index()
    {

        var entity = await _context.Products.ToListAsync();

        return View(entity);
    }

    [EnableRateLimiting("FixedLimiter")]
    public async Task<IActionResult> OurShop(int page =1)
    {

        int pageSize = 10;
        var products = new List<Product>();
        var categories = new List<Category>();  
        if(_appCache.TryGetValue("categoriesOurShop", out List<Category> categoriesCache))
        {
            categories = categoriesCache;
        }   
        else
        {
            categories = await _context.Categories.ToListAsync();
            _appCache.Add("categoriesOurShop", categories);
        }

        if(_appCache.TryGetValue("productsOurShop",out List<Product> productsCache))
        {
            products = productsCache;
        }
        else
        {
            products = await _context.Products.ToListAsync();
            _appCache.Add("productsOurShop", products);
        }
        
        var paginatedList = products.ToPagedList(page, pageSize);
        var ProductAndCategoryViewModels = new ProductAndCategoryViewModels()
        {
            Products = paginatedList,
            Categories = categories
        };


        return View(ProductAndCategoryViewModels);
    }

    [EnableRateLimiting("SlidingLimiter")]
    public async Task<IActionResult> ProductDetails(Guid? id)
    {
        if(id == null)
        {
            return RedirectToAction("OurShop");
        }

        var entity =await _context.Products.FindAsync(new object[] { id });
        return View(entity);
    }


    [EnableRateLimiting("SlidingLimiter")]
    [Authorize(Roles ="farfar")]
    public IActionResult Contact()
    {
        return View();
    }

    [EnableRateLimiting("SlidingLimiter")]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Gaming.MVC/Views/Home/Contact.cshtml
@{
}
@model Gaming.MVC.Models.ContactSended

<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Contact Us</h3>
                <span class="breadcrumb"><a asp-action="Index" asp-controller="Home">Home</a>  >  Contact Us</span>
            </div>
        </div>
    </div>
</div>

<div class="contact-page section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 align-self-center">
                <div class="left-text">
                    <div class="section-heading">
                        <h6>Contact Us</h6>
                        <h2>Say Hello!</h2>
                    </div>
                    <p>LUGX Gaming Template is based on the latest Bootstrap 5 CSS framework. This template is provided by TemplateMo and it is suitable for your gaming shop ecommerce websites. Feel free to use this for any purpose. Thank you.</p>
                    <ul>
                        <li><span>Address</span> Sunny Isles Beach, FL 33160, United States</li>
                        <li><span>Phone</span> +123 456 7890</li>
                        <li><span>Email</span> lugx@contact.com</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="right-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="map">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth" width="100%" height="325px" frameborder="0" style="border:0; border-radius: 23px;" allowfullscreen=""></iframe>
                            </div>
                        </div>
                        @if ( Model!=null)
                        {
                            <div class="alert alert-success" id="success-alert">
                                <button type="button" class="close" data-bs-dismiss="alert">x</button>
                                <strong>Success! </strong> Product have added to your wishlist.
                            </div>
                            
                        }
                       
                        <div class="col-lg-12">
                            <form asp-action="Post" enctype="multipart/form-data" asp-controller="Bot">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="row">

                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input asp-for="ContactUs.Name" placeholder="Your Name...">
                                            <span asp-validation-for="ContactUs.Name" class="text-danger"></span>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input asp-for="ContactUs.Surname" placeholder="Your Surname..." required>
                                            <span asp-validation-for="ContactUs.Surname" class="text-danger"></span>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input asp-for="ContactUs.Email" placeholder="Your E-mail..." >
                                            <span asp-validation-for="ContactUs.Email" class="text-danger"></span>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-6">
                                        <fieldset>
                                            <input asp-for="ContactUs.Subject" placeholder="Subject...">
                                            <span asp-validation-for="ContactUs.Subject" class="text-danger"></span>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-12">
                                        <fieldset>
                                            <textarea asp-for="ContactUs.Message" placeholder="Your Message"></textarea>
                                            <span asp-validation-for="ContactUs.Message" class="text-danger"></span>
                                        </fieldset>
                                    </div>
                                    <div class="col-lg-12">
                                        <fieldset>
                                            <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                                        </fieldset>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>  

Gaming.MVC/Views/Home/OurShop.cshtml
@model Gaming.MVC.Models.ProductAndCategoryViewModels
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@{
}

<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Our Shop</h3>
                <span class="breadcrumb"><a asp-action="Index" asp-controller="Home">Home</a> > Our Shop</span>
            </div>
        </div>
    </div>
</div>

<div class="section trending">
    <div class="container">
       
        <ul class="trending-filter">

            <li>
                <a class="is_active" href="#!" data-filter="*">Show All</a>
            </li>
            @foreach (var category in Model.Categories)
            {

                <li>
                    <a href="#!" data-filter=".@category.CategoryName">@category.CategoryName</a>
                </li>
            }

          
        </ul>
            <div class="row trending-box">
        @foreach (var game in Model.Products)
        {
                <div class="col-lg-3 col-md-6 align-self-center mb-30 trending-items col-md-6 @game.Category.CategoryName">
                    <div class="item">
                        <div class="thumb">
                            <a asp-action="ProductDetails" asp-controller="Home" asp-route-id="@game.ProductId"><img src="@game.ProductImage" asp-append-version="true" alt=""></a>
                            <span class="price"><em>@if(game.Discount>0)@("$"+game.Price)</em>$@(game.Price-game.Discount)</span>
                        </div>
                        <div class="down-content">
                            <span class="category">@game.Category.CategoryName</span>
                            <h4>@game.ProductName</h4>
                            <a asp-action="ProductDetails" asp-controller="Home" asp-route-id="@game.ProductId"><i class="fa fa-shopping-bag"></i></a>
                        </div>
                    </div>
                </div>

        }
            </div>

        <div class="container d-flex align-items-center justify-content-center">
            @Html.PagedListPager((IPagedList)Model.Products, page => Url.Action("OurShop", new { page = page }),
            new X.PagedList.Web.Common.PagedListRenderOptions
            {
            DisplayItemSliceAndTotal = false,
            ContainerDivClasses = new[] { "navigation" },
            LiElementClasses = new[] { "page-item" },
            PageClasses = new[] { "page-link" },
            })

        </div>
    </div>
</div>

Gaming.MVC/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Lugx Gaming Shop HTML5 Template</title>

    <!-- Bootstrap core CSS -->

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />



    <!-- Additional CSS Files -->
    
    <link rel="stylesheet" href="~/lib/css/fontawesome.css">
    <link rel="stylesheet" href="~/lib/css/templatemo-lugx-gaming.css">
    <link rel="stylesheet" href="~/lib/css/owl.css">
    <link rel="stylesheet" href="~/lib/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!--

    TemplateMo 589 lugx gaming


    -->
</head>

<body>
    @using Gaming.Application.Common.Interfaces;
    @using Gaming.Domain.Identity;
    @using Microsoft.AspNetCore.Identity;
    @inject ICurrentUser _currentUser
    @inject UserManager<User> _usermanager
    @{
        var CurrentUser =await _usermanager.FindByIdAsync(_currentUser.UserId);
    }
   
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a asp-action="Index" asp-controller="Home" class="logo">
                            <img src="~/images/logo.png" alt="" style="width: 158px;">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                            <li><a asp-action="OurShop" asp-controller="Home">Our Shop</a></li>
                            
                            <li><a asp-action="Contact" asp-controller="Home">Contact Us</a></li>
                            @{

                                if (!User.Identity?.IsAuthenticated??false || CurrentUser?.Id == null)
                                {
                                    <li><a asp-area="Identity" asp-page="/Account/Login">Sign In</a></li>

                                }
                                else
                                {

                                    <li>
                                        <a asp-area="Identity" asp-page="/Account/Manage/Index" class=" d-flex justify-content-evenly">
                                            My profile
                                            <img class="styleofProfilePicture" src="@CurrentUser?.ProfilePicture" />
                                        </a>
                                    </li>
                                    <li><a asp-area="Identity" asp-page="/Account/Logout">Logout</a></li>
                                   
                                   
                                }
        
                            }
                             
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
    @RenderBody()
    <footer>
        <div class="container">
            <div class="col-lg-12">
                <p>Copyright © 2048 LUGX Gaming Company. All rights reserved. &nbsp;&nbsp; <a rel="nofollow" href="https://templatemo.com" target="_blank">Design: TemplateMo</a></p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->


    <style>
        .styleofProfilePicture {
            margin-left:5px;
            border:2px solid #fff;
            border-radius: 50%;
            width:45px;
            height:40px;
            cursor:pointer;
            
            
        }

        .styleofProfilePicture:hover{
            opacity:0.5;
           
        }
        
    </style>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/isotope.min.js"></script>
    <script src="~/js/owl-carousel.js"></script>
    <script src="~/js/counter.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Gaming.MVC/Views/Home/productDetails.cshtml
@model Gaming.Domain.Entities.Product;
@{
   
}

<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>@Model.ProductName</h3>
                <span class="breadcrumb"><a asp-action="Index" asp-controller="Home">Home</a>  >  <a href="#">Shop</a>  >  Assasin Creed</span>
            </div>
        </div>
    </div>
</div>

<div class="single-product section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-image">
                    
                    <img src="@Model.ProductImage" alt="">
                </div>
            </div>
            <div class="col-lg-6 align-self-center">
                <h4>@Model.ProductName</h4>
                <span class="price"><em>@if (Model.Discount > 0)@("$" + Model.Price)</em>$@(Model.Price - Model.Discount)</span>
                <p>LUGX Gaming Template is based on the latest Bootstrap 5 CSS framework. This template is provided by TemplateMo and it is suitable for your gaming shop ecommerce websites. Feel free to use this for any purpose. Thank you.</p>
               
                <form asp-action="CreateCart" asp-controller="Carts"  >
                    <input type="hidden" name="productId" value="@Model.ProductId" />
                    <input type="number" class="form-control" name="quantity" value="1" placeholder="1">
                    <button type="submit"><i class="fa fa-shopping-bag"></i> ADD TO CART</button>
                </form>
               
                <ul>
                    <li><span>Game ID:</span> @Model.ProductId</li>
                    <li><span>Genre:</span> <a href="#">@Model.Category.CategoryName</a>, <a href="#">Team</a>, <a href="#">Single</a></li>
                    <li><img src="@Model.Category.CategoryImage"/></li>
                    <li><span>Multi-tags:</span> <a href="#">War</a>, <a href="#">Battle</a>, <a href="#">Royal</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="sep"></div>
            </div>
        </div>
    </div>
</div>

<div class="more-info">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-content">
                    <div class="row">
                        <div class="nav-wrapper ">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="true">Description</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="false">Reviews (3)</button>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                                <p>You can search for more templates on Google Search using keywords such as "templatemo digital marketing", "templatemo one-page", "templatemo gallery", etc. Please tell your friends about our website. If you need a variety of HTML templates, you may visit Tooplate and Too CSS websites.</p>
                                <br>
                                <p>Coloring book air plant shabby chic, crucifix normcore raclette cred swag artisan activated charcoal. PBR&B fanny pack pok pok gentrify truffaut kitsch helvetica jean shorts edison bulb poutine next level humblebrag la croix adaptogen. Hashtag poke literally locavore, beard marfa kogi bruh artisan succulents seitan tonx waistcoat chambray taxidermy. Same cred meggings 3 wolf moon lomo irony cray hell of bitters asymmetrical gluten-free art party raw denim chillwave tousled try-hard succulents street art.</p>
                            </div>
                            <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                                <p>Coloring book air plant shabby chic, crucifix normcore raclette cred swag artisan activated charcoal. PBR&B fanny pack pok pok gentrify truffaut kitsch helvetica jean shorts edison bulb poutine next level humblebrag la croix adaptogen. <br><br>Hashtag poke literally locavore, beard marfa kogi bruh artisan succulents seitan tonx waistcoat chambray taxidermy. Same cred meggings 3 wolf moon lomo irony cray hell of bitters asymmetrical gluten-free art party raw denim chillwave tousled try-hard succulents street art.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section categories related-games">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-heading">
                    <h6>Action</h6>
                    <h2>Related Games</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="main-button">
                    <a href="shop.html">View All</a>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="~/lib/images/categories-01.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="~/lib/images/categories-05.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="~/lib/images/categories-03.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="~/lib/images/categories-04.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="~/lib/images/categories-05.jpg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>